[platformio]
default_envs = d1_mini

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  knolleary/PubSubClient@^2.8
  olikraus/U8g2@^2.36.5
